export enum KijijiCategory {
  ArtsAndCollectibles = "Arts & Collectibles",
  Audio = "Audio",
  BabyItems = "Baby Items",
  Bikes = "Bikes",
  Books = "Books",
  BusinessAndIndustrial = "Business & Industrial",
  CamerasAndCamcorders = "Cameras & Camcorders",
  CDsDVDsAndBluray = "CDs, DVDs & Blu-ray",
  Clothing = "Clothing",
  Computers = "Computers",
  ComputerAccessories = "Computer Accessories",
  Electronics = "Electronics",
  FreeStuff = "Free Stuff",
  Furniture = "Furniture",
  GarageSales = "Garage Sales",
  HealthAndSpecialNeeds = "Health & Special Needs",
  HobbiesAndCrafts = "Hobbies & Crafts",
  HomeAppliances = "Home Appliances",
  HomeIndoor = "Home - Indoor",
  HomeOutdoorAndGarden = "Home - Outdoor & Garden",
  HomeRenovationMaterials = "Home Renovation Materials",
  JewelleryAndWatches = "Jewellery & Watches",
  MusicalInstruments = "Musical Instruments",
  Phones = "Phones",
  SportingGoodsAndExercise = "Sporting Goods & Exercise",
  Tools = "Tools",
  ToysAndGames = "Toys & Games",
  TVsAndVideo = "TVs & Video",
  VideoGamesAndConsoles = "Video Games & Consoles",
}

export enum KijijiMusicalInstrumentCategory {
  AmpsAndPedals = "Amps & Pedals",
  Brass = "Brass",
  DrumsAndPercussion = "Drums & Percussion",
  Guitars = "Guitars",
  PerformanceAndDJEquipment = "Performance & DJ Equipment",
  PianosAndKeyboards = "Pianos & Keyboards",
  ProAudioAndRecordingEquipment = "Pro Audio & Recording Equipment",
  String = "String",
  Woodwind = "Woodwind",
  Other = "Other",
}

export enum KijijiClothingCategory {
  Costumes = "Costumes",
  KidsAndYouth = "Kids & Youth",
  Mens = "Men's",
  MensShoes = "Men's Shoes",
  MultiItem = "Multi-item",
  Wedding = "Wedding",
  WomensBagsAndWallets = "Women's - Bags & Wallets",
  WomensBottoms = "Women's - Bottoms",
  WomensDressesAndSkirts = "Women's - Dresses & Skirts",
  WomensMaternity = "Women's - Maternity",
  WomensShoes = "Women's - Shoes",
  WomensTopsAndOuterwear = "Women's - Tops & Outerwear",
  Other = "Other",
  WomensOther = "Women's - Other",
}

export enum ShopifyCategory {
  ApparelAndAccessories = "Apparel & Accessories",
  ArtsAndCrafts = "Arts & Crafts",
  Automotive = "Automotive",
  BabyAndKids = "Baby & Kids",
  BeautyAndPersonalCare = "Beauty & Personal Care",
  BooksAndStationery = "Books & Stationery",
  ConsumerElectronics = "Consumer Electronics",
  FoodAndBeverages = "Food & Beverages",
  Furniture = "Furniture",
  HealthAndWellness = "Health & Wellness",
  HomeAndLiving = "Home & Living",
  JewelryAndWatches = "Jewelry & Watches",
  MusicalInstruments = "Musical Instruments",
  OfficeSupplies = "Office Supplies",
  PetSupplies = "Pet Supplies",
  ShoesAndFootwear = "Shoes & Footwear",
  SportingGoods = "Sporting Goods",
  ToysAndGames = "Toys & Games",
  TravelAndLuggage = "Travel & Luggage",
  VideoGamesAndConsoles = "Video Games & Consoles",
  Other = "Other",
}

export enum ShopifySubCategory {
  SomeTestSubCategory = "Some Test SubCategory",
}
